version: "3"
services:
  mongo:
    container_name: mongo
    privileged: true
    env_file: .env
    build:
      context: ./services/mongo
      args:
        - MONGO_VERSION=${MONGO_VERSION}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${DATA_DIR}/mongo:/data/db
      - ${MONGO_CONF_DIR}:/data/configdb
      - ${LOG_DIR}/mongo/mongod.log:/var/log/mongodb/mongod.log
    restart: always
    command: mongod --oplogSize 128
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - lnmp-net
networks:
  lnmp-net:
    external: true

